### ISSUE TITLE
Behavior with Horde Lullaby

### ISSUE THREAD

**Issue by bgoodtimes** [ThornyFFXI/tTimers#11] opened 2024-02-18 01:09 UTC
When hitting multiple targets it correctly times 1 instance of the sleep in the debuff list with the target mob, but an additonal one will show up under the buffs list with the other mob name next to it.

**Comment by ThornyFFXI** [comment] 2024-02-18 12:02
I was unable to reproduce a condition where horde lullaby produces a buff entry on retail.  That said, it was not correctly tracking multiple targets, so I did adjust the message IDs in 0.08.  I suspect this will not fix your issue, as it's likely your private server is using the wrong message IDs.  If you could provide the exact text that appears when you cast Horde, I can assess further.

**Comment by WinterSolstice8** [comment] 2024-03-11 00:36
> private server is using the wrong message IDs.

That is correct, this change is relatively recent to mimic retails behavior.

https://github.com/LandSandBoat/server/pull/3988

**Comment by ThornyFFXI** [comment] 2024-03-12 13:48
Closing this then, thank you for verifying.

**Closed by ThornyFFXI** 2024-03-12 13:48 UTC
