### ISSUE TITLE
Drop down menu's not functioning correctly

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/tTimers#2] opened 2024-02-10 20:02 UTC
I'll try to describe this as short as I can using steps to reproduce.

I click on recast tab, the panel skin option shows "windower"
I change it to "windower_bottom_justified"
I can visually see the change take effect on my current recasts
I click to the buff tab
I click back to the recast tab and the panel skin has gone back to "windower"
Visually nothing changes, still looks like windower_bottom_justified
I do not change the option again
I open the settings.lua file for my active char, and it still shows "settings["Recast"]["Skin"]["classic"] = "windower_bottom_justified";"
The UI combo selector still shows "windower"

The actual effect seems to be functioning just fine but the imgui.combo (or w/e that drop down is) is just not displaying the current selected option correctly.

Further, I tried the Sort Type drop down to see if the same thing is happening there, and the option seems to be maintaining its state while clicking different tabs however if I change this drop down for the Recast tab for example, it will also change the sort types for buff and debuff tabs as well. I am not sure if this is intentional or not.

**Comment by ThornyFFXI** [comment] 2024-02-10 20:10
definitely not intended behavior, will look into it tonight or tomorrow

probably to do with imgui elements having the same name, shouldnt be too bad a fix

**Comment by ThornyFFXI** [comment] 2024-02-10 21:56
fixed in 0.03

**Closed by ThornyFFXI** 2024-02-10 21:56 UTC
